/* What has landed, from docs/decisions.md status notes and the git log. Images are the template's abstract cover art. */
export const CHANGELOG = [
  { version: "Phase 0 · Recon", date: "Sep 17, 2026", title: "Every assumption about the tokens, checked", body: "<p>Ratios, custody, pausability, liquidity and price feeds for all Mag 7 representations on BSC, verified against Sourcify sources and live pools. Ondo's ratio is API-only; bStocks expose it onchain. bStocks have deep PancakeSwap USDT pools; Ondo trades through RFQ desks.</p><ul><li><p>NVDAB pool $1.24M at 0.25%; NVDAon $8.7k at 1%</p></li><li><p>Chainlink push feeds live for all seven names</p></li><li><p>Blocked items and their fallbacks recorded in docs/recon.md §8</p></li></ul>", image: "p80IM1v24rHW518e6PISttTXiE.png" },
  { version: "Phase 1 · Contracts", date: "Sep 18, 2026", title: "StockRegistry, ShareRouter, BasketVault, AgentMandate", body: "<p>102 unit, fuzz and invariant tests plus 6 mainnet-fork tests pass, with 100% line coverage on the core contracts and a clean Slither run. Deploy scripts verified on a local fork with real tokens (pxMAG7) and on a mocks chain (pxDEMO3).</p><ul><li><p>Handler-based invariants for the vault and the mandate</p></li><li><p>Every revert path has a test; the share math is fuzzed</p></li><li><p>16 medium and low Slither findings dispositioned in docs/threat-model.md</p></li></ul>", image: "hDek95VWPmNm03w03MHmvwwNg.png" },
  { version: "Phase 3 · Resolver", date: "Sep 19, 2026", title: "End to end on a mainnet fork", body: "<p>$100 of NVDA resolved to NVDAB at $219.01 per share, 8 bps under the Chainlink reference. One pxMAG7 unit minted through seven legs for $98.52 against a $98.35 NAV, redeemed to USDT, then redeemed in kind, with every receipt indexed and linked to its scoring record.</p><ul><li><p>Backing 1.0001 on every constituent after the mint</p></li><li><p>18 resolver tests on the mocks chain</p></li><li><p>Migration through the 1% pool refused as not share-accretive</p></li></ul>", image: "11xG1sFHVj6lM1DVlbha1QHUOA.png" },
  { version: "Phase 5 · Agents", date: "Sep 19, 2026", title: "MCP server, writes only through the mandate", body: "<p>Seven end-to-end tests with the official MCP client over stdio: search, resolve, mandate read and build, an agent buy and a basket mint through the mandate, per-transaction and daily cap refusals, allowlist refusal, revocation and receipt explanation.</p><ul><li><p>Simulation before every send; refusals explained before gas</p></li><li><p>Outputs hardcoded to the owner</p></li><li><p>quote_hash on every answer</p></li></ul>", image: "EK5aqe0bRCriNIymfbiKUN8o.png" },
  { version: "M1–M3 · Aggregator", date: "Sep 20, 2026", title: "Execution through the Binance aggregator, and its limit", body: "<p>An aggregator leg executed through ShareRouter on a fork at head: 0.900979 NVDA shares credited via Uniswap V3 for 452k gas. The resolver returns signable aggregator transactions. Three index vaults (pxMAG7, pxAI, pxNEW) created on the fork at about $100 per unit; pxMAG7 quoted at $1,005.65 for 10 units across seven legs.</p><ul><li><p>Pure-AMM routes replay on a fork; RFQ and PMM desk routes do not</p></li><li><p>Mainnet deployment costed at $1.32 from testnet receipts</p></li><li><p>Quote-only mode runs the search product against mainnet with nothing deployed</p></li></ul>", image: "y0yJSJrbAEeeZQJ3vgVgvfDKt8.png" },
  { version: "Audit · Fuzzing", date: "Sep 21, 2026", title: "Six findings, fixed; 93 properties, clean", body: "<p>A twelve-agent audit round over the contracts, then a stateful Medusa campaign. Six findings survived deduplication and gating, and all six were fixed the same day: a mint that could draw on another holder's backing slack, an agent able to divert its owner's swap output, absolute-balance refunds in the router and the mandate, an issuer cap that could brick a vault, and keeper ratio steps that compounded.</p><ul><li><p>The fuzzer found a real one: summing per-representation floors against a ceiled requirement left a vault one wei under-backed after a pro-rata burn, so the next exact mint reverted. Backing is now compared exactly.</p></li><li><p>124 Foundry tests, 93 fuzz properties, 270,136 calls, zero failures</p></li><li><p>96-100% line coverage on the core contracts</p></li></ul>", image: "y0yJSJrbAEeeZQJ3vgVgvfDKt8.png" },
  { version: "Mainnet", date: "Sep 22, 2026", title: "Live on BNB Smart Chain", body: "<p>StockRegistry, ShareRouter, BasketFactory, AgentMandate and the pxMAG7, pxAI and pxNEW vaults are deployed on chain 56, for 0.00183 BNB at 0.05 gwei. The registry holds the 19 stocks the three indices need and their 36 Ondo and bStocks tokens, with Chainlink USD feeds wired for the Mag 7 and the protocol fee set to 0.5%.</p><ul><li><p>A $100 pxMAG7 quote fills all seven legs: five through PancakeSwap pools, two through the aggregator's desk</p></li><li><p>Index minimums now come from venue liquidity rather than a constant, because AAPL and AMZN have no usable pool on BSC</p></li><li><p>Returns for every period on every index, from Chainlink where it reaches and daily closes where it does not</p></li></ul>", image: "y0yJSJrbAEeeZQJ3vgVgvfDKt8.png" },
];
