/* Legal pages for a hackathon prototype. Plain, short, honest. */
export const LEGALS: Record<string, { title: string; pageTitle: string; body: string }> = {
  "privacy-policy": {
    title: "Privacy Policy",
    pageTitle: "Parallax - Privacy Policy",
    body: "<p><strong>Last updated: September 20, 2026</strong></p><p><strong>1. What this is</strong> Parallax is a hackathon prototype built for BNB Hack: Tokenized Stocks Edition. This page explains what the site and the app record about you, which is very little.</p><p><strong>2. What we collect</strong> The web app runs in your browser and talks to a resolver service. The resolver logs the requests it serves (ticker, amount, policy, the wallet address you pass for simulation) and stores quote records keyed by their hash so that an onchain receipt can be linked back to the scoring that produced it. It does not collect names, emails or analytics. The contact form on this site does not submit anywhere.</p><p><strong>3. Onchain data</strong> Anything you sign is public on BNB Chain, including your address, the tokens bought and the receipt emitted by the router or vault. That is the nature of the chain, not a choice we make.</p><p><strong>4. Third parties</strong> Prices and catalogue data come from the Binance Web3 API and Chainlink feeds; swaps route through PancakeSwap, the Binance aggregator and the venues behind it. Their terms apply to their services.</p><p><strong>5. Retention</strong> Quote records and receipts are kept in the resolver's database for as long as the service runs. Ask and we will delete anything keyed to your address.</p><p><strong>6. Contact</strong> Open an issue at <a href=\"https://github.com/Adityaakr/parallax\">github.com/Adityaakr/parallax</a>.</p>",
  },
  "terms-of-service": {
    title: "Terms of Service",
    pageTitle: "Parallax - Terms of Service",
    body: "<p><strong>Last updated: September 20, 2026</strong></p><p><strong>1. What you are using</strong> Parallax is unaudited hackathon software. It routes purchases of tokenized stocks on BNB Chain and manages share-defined baskets. It is not investment advice and it is not an offer to sell securities. Tokenized stock availability depends on your jurisdiction and on each issuer's terms.</p><p><strong>2. No custody</strong> Parallax never holds your funds. You sign every transaction yourself, or an agent acts through a mandate you created and can revoke at any time. Outputs always go to the wallet that owns the mandate.</p><p><strong>3. What can go wrong</strong> Issuers can pause or blocklist their tokens. Keepers can post stale data, within the bounds the contracts enforce. Venues can re-price. The contracts are written to fail closed and to keep in-kind redemption open regardless, and the tests for that are public, but a prototype is a prototype.</p><p><strong>4. No fees, no token</strong> Parallax charges no protocol fee and has no token. You pay network gas on your own transactions.</p><p><strong>5. Trust assumptions</strong> The admin is a deployer EOA for the hackathon. The keeper posts Ondo ratios, attestation timestamps and market state under step and freshness limits. Both are stated in the repository rather than hidden.</p><p><strong>6. Liability</strong> To the extent the law allows, the authors are not liable for losses arising from use of this software. Use it with amounts you can afford to lose while it is a prototype.</p><p><strong>7. Contact</strong> Open an issue at <a href=\"https://github.com/Adityaakr/parallax\">github.com/Adityaakr/parallax</a>.</p>",
  },
};
