// SPDX-License-Identifier: MIT
pragma solidity >=0.6.2 <0.9.0;

import {Test} from "forge-std/Test.sol";
import {console} from "forge-std/console.sol";
import {Handlers} from "./handlers/Handlers.sol";

/// @notice Contract to be used for quick testing with Foundry
contract FoundryTester is Test, Handlers {
    modifier asActor() override {
        vm.startPrank(actor);
        _;
        vm.stopPrank();
    }

    function setUp() public {
        setup();
    }

    // forge test --match-test test_sequence -vvv
    function test_sequence() public {
        // smoke: every primary path once, at fair execution
        shareRouter_buyShares_clamped(1_000e6, 1, 0, actor);
        shareRouter_sellShares_clamped(1e18, 1, true, actor);
        basketVault_mint_clamped(5e18, 7_000, actor);
        basketVault_mint_underDelivered(1e18, 0);
        basketVault_mint_underDelivered(1e18, 1);
        basketVault_redeem_clamped(1e18, 5_000, actor);
        basketVault_redeemInKind_clamped(1e18, actor);
        environment_secondary(0, 200e18, 1, actor); // NVDAB cheaper -> ondo->bstock migration gains shares
        basketVault_migrate_clamped(1_000, true, 0);
        agentMandate_createMandate_clamped(500e6, 1000e6, 7, 300, true, true, true);
        agentMandate_agentBuyShares_clamped(0, 100e6, 1, 0);
        agentMandate_agentMintBasket_clamped(0, 1e18, 7_000);
        stockRegistry_secondary(4, 1.005e18, 0, 0);
        environment_warp(1 hours);
        basketVault_redeem_full(uint16(BPS));
        assertTrue(basket.backingOk());
    }

    // ── Violation Repros (auto-generated by Step 11) ──────────────────

    /// Regression for the rounding gap the campaign found: a pro-rata burn left heldShares (sum of floors) one
    /// wei under requiredShares (ceil). Backing is now compared exactly, so the burn keeps backing.
    function test_repro_burnKeepsBackingExactly() public {
        basketVault_mint_dust(2335525000000000017167, 26522);
        assertTrue(basket.backingOk());
        basketVault_secondary(141, 7237005577332262213973186563042994240829374041602535252464913625989141142508, address(0x6f05b59d3b20000), 17);
        assertTrue(basket.backingOk(), "burn must not break backing");
    }
    // Each test_repro_* function below replays a shrunk fuzzer call
    // sequence that violated a property. Run all with:
    //   forge test --match-contract FoundryTester -vvv
}
