/**
 * Regenerates contracts/script/config/mocks.json — the mock universe deployed on BSC testnet (97) and the local
 * mocks chain (1337) — from the real one in bsc.json.
 *
 * Every representation of every index constituent becomes a mock token that is *twinned* with its mainnet
 * token (`mainnetToken`): the resolver reads that twin's live catalogue price, reference price and market state,
 * and the keeper mirrors the twin's price and ERC-8056 multiplier onto the mock venue. The seed price and ratio
 * written here are only the venue's opening values; the keeper overwrites them within a minute of starting.
 *
 *   BINANCE_WEB3_API_KEY=… BINANCE_WEB3_API_SECRET=… npx tsx scripts/gen-mocks.mts [--write]
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { BinanceWeb3Client } from "@parallax-hood/binance-client";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const bsc = JSON.parse(readFileSync(resolve(ROOT, "contracts/script/config/bsc.json"), "utf8")) as {
  representations: { ticker: string; platform: string; symbol: string; token: string; source: string; initialRatio: string }[];
  indices: { symbol: string; constituents: { ticker: string }[] }[];
};
const previous = JSON.parse(readFileSync(resolve(ROOT, "contracts/script/config/mocks.json"), "utf8")) as { basket: unknown };

const c = new BinanceWeb3Client({ apiKey: process.env.BINANCE_WEB3_API_KEY!, apiSecret: process.env.BINANCE_WEB3_API_SECRET!, mode: "live" });
const live = new Map((await c.rwaTokens({ binanceChainId: "56" })).map((t) => [t.tokenContractAddress.toLowerCase(), t]));

const wad = (v: string | null | undefined) => {
  const [i = "0", f = ""] = String(v ?? "0").split(".");
  return (BigInt(i) * 10n ** 18n + BigInt((f + "0".repeat(18)).slice(0, 18))).toString();
};

const tickers = [...new Set(bsc.indices.flatMap((i) => i.constituents.map((x) => x.ticker)))].sort();
const representations = bsc.representations
  .filter((r) => tickers.includes(r.ticker))
  .map((r) => {
    const t = live.get(r.token.toLowerCase());
    if (!t?.tokenPrice) throw new Error(`no live price for ${r.symbol} (${r.token}); refusing to seed a mock without one`);
    return {
      ticker: r.ticker, platform: r.platform, symbol: r.symbol, mainnetToken: r.token,
      erc8056: r.source === "ERC8056",
      ratio: wad(t.tokenToShareRatio ?? "1"),
      // catalogue tokenPrice is USD per raw token, which is exactly what the mock venue prices in
      tokenPriceUsd: wad(t.tokenPrice),
    };
  });

const out = {
  _note: "Generated by scripts/gen-mocks.mts from bsc.json: every representation of every index constituent, twinned with its mainnet token. Used on BSC testnet (97) and local anvil without a fork. Seed prices are opening values; the keeper mirrors mainnet onto the venue.",
  _generatedAt: new Date().toISOString(),
  underlyings: tickers,
  representations,
  basket: previous.basket,
};
const json = JSON.stringify(out, null, 2) + "\n";
if (process.argv.includes("--write")) {
  writeFileSync(resolve(ROOT, "contracts/script/config/mocks.json"), json);
  console.log(`wrote mocks.json: ${tickers.length} underlyings, ${representations.length} representations`);
} else {
  console.log(json);
}
