import { chromium } from "playwright";
const b = await chromium.launch();
const p = await b.newPage({ viewportSize: { width: 1440, height: 1200 }, deviceScaleFactor: 2 });
await p.goto("http://127.0.0.1:3100/baskets/pxMAG7", { waitUntil: "networkidle", timeout: 180000 }).catch(() => {});
await p.waitForTimeout(7000);
await p.screenshot({ path: "/tmp/toolbar.png", clip: { x: 0, y: 60, width: 1440, height: 130 } });
const panel = p.locator("text=You invest").first().locator("xpath=ancestor::*[contains(@class,'panel')][1]");
await panel.screenshot({ path: "/tmp/invest.png" }).catch((e) => console.log("invest", e.message.slice(0,60)));
await p.getByRole("button", { name: "Redeem", exact: true }).first().click().catch(() => {});
await p.waitForTimeout(4000);
await panel.screenshot({ path: "/tmp/redeem.png" }).catch((e) => console.log("redeem", e.message.slice(0,60)));
await b.close();
