import { chromium } from "playwright";
const b = await chromium.launch();
const p = await b.newPage({ viewportSize: { width: 1440, height: 1200 }, deviceScaleFactor: 2 });
await p.goto("http://127.0.0.1:3100/blog/how-an-order-travels", { waitUntil: "networkidle", timeout: 180000 }).catch(() => {});
await p.waitForTimeout(4000);
await p.evaluate(() => window.scrollTo(0, 900));
await p.waitForTimeout(2500);
const fig = p.locator("figure.diagram").first();
await fig.scrollIntoViewIfNeeded();
await p.waitForTimeout(2500);
await fig.screenshot({ path: "/tmp/diagram.png" });
await p.goto("http://127.0.0.1:3100/blog", { waitUntil: "networkidle", timeout: 120000 }).catch(() => {});
await p.waitForTimeout(3000);
await p.screenshot({ path: "/tmp/blog-index.png", clip: { x: 0, y: 620, width: 1440, height: 900 } });
await b.close();
