import { chromium } from "playwright";
const [route, out, width = "1440"] = process.argv.slice(2);
const b = await chromium.launch(); const p = await b.newPage({ viewport: { width: +width, height: 900 } });
if (process.env.CHAIN) await p.addInitScript((c) => localStorage.setItem("parallax:chain", c), process.env.CHAIN);
const errs = []; p.on("pageerror", (e) => errs.push(e.message)); p.on("console", (m) => { if (m.type() === "error") errs.push(m.text()); });
await p.goto("http://127.0.0.1:3100" + route, { waitUntil: "domcontentloaded", timeout: 90000 });
await p.waitForTimeout(9000);
await p.evaluate(async () => { const h = document.documentElement.scrollHeight; for (let y = 0; y < h; y += 300) { window.scrollTo(0, y); await new Promise(r => setTimeout(r, 40)); } window.scrollTo(0, 0); });
await p.waitForTimeout(800);
await p.screenshot({ path: out, fullPage: true });
console.log("wrote", out, "errors:", errs.slice(0, 5));
await b.close();
